<a href="https://colab.research.google.com/github/KodumuruRaja/Crash-Courses/blob/main/Numpy-(Crash-Course).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# List and Numpy Array
list1=[0,1,2,3,4]

In [ ]:
list1

[0, 1, 2, 3, 4]

In [ ]:
arr1d=np.array(list1)

In [ ]:
arr1d

array([0, 1, 2, 3, 4])

In [ ]:
list1.append(5)

In [ ]:
list1

[0, 1, 2, 3, 4, 5]

In [ ]:
arr1d + 2

array([2, 3, 4, 5, 6])

In [ ]:
list2=[[1,1,1],[2,2,2],[3,3,3]]
arr2d=np.array(list2)

In [ ]:
arr2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
type(arr2d)

numpy.ndarray

In [ ]:
arr2d.dtype

dtype('int64')

In [ ]:
#converting int64 numpy array to float
arr2d=np.array(list2,dtype='float')

In [ ]:
arr2d.dtype

dtype('float64')

In [ ]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [ ]:
#change dtype of array
arr2d=arr2d.astype('int')

In [ ]:
list1.append('6')

In [ ]:
list1

[0, 1, 2, 3, 4, 5, '6']

In [ ]:
#changing array to list
np2list=arr2d.tolist()

In [ ]:
np2list

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [ ]:
#array to string
arr2d.tostring()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  


b'\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00'

In [ ]:
#array to bytes
arr2d.tobytes()

b'\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00'

# **dtype and shape**

In [ ]:
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [ ]:
arr2d=arr2d.astype('float')

In [ ]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [ ]:
print("Shape:", arr2d.shape)

Shape: (3, 3)


In [ ]:
arr2d.dtype

dtype('float64')

In [ ]:
arr2d.size

9

In [ ]:
arr1d.size

5

In [ ]:
arr2d.ndim

2

In [ ]:
arr1d.ndim

1

In [ ]:
arr1d=arr1d*arr1d

In [ ]:
arr1d

array([ 0,  1,  4,  9, 16])

In [ ]:
arr1d[0]

0

In [ ]:
arr1d[3]

9

In [ ]:
arr1d[0:4]

array([0, 1, 4, 9])

In [ ]:
arr1d[1:3]

array([1, 4])

In [ ]:
arr1d[:3]

array([0, 1, 4])

In [ ]:
arr1d[1:]

array([ 1,  4,  9, 16])

In [ ]:
arr2d=arr2d.astype('int')

In [ ]:
arr2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
arr2d[0][0]

1

In [ ]:
arr2d[1][0]

2

In [ ]:
boolarr=arr2d<3

In [ ]:
boolarr

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
arr2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
#to reverse the array
#here rows are changed
arr2d[::-1]

array([[3, 3, 3],
       [2, 2, 2],
       [1, 1, 1]])

In [ ]:
#here rows and columns are changed
arr2d[::-1,::-1]

array([[3, 3, 3],
       [2, 2, 2],
       [1, 1, 1]])

In [ ]:
arr2d=arr2d.astype('float')

In [ ]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

# **np.nan, np.inf**

In [ ]:
np.nan

nan

In [ ]:
np.inf

inf

In [ ]:
arr2d[0][0]=np.nan
arr2d[0][1]=np.inf
arr2d

array([[nan, inf,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [ ]:
np.isnan(arr2d)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.isinf(arr2d)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
mf=np.isnan(arr2d) | np.isinf(arr2d)
mf

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
#replace inf and nan with zero(0)
arr2d[mf]

array([nan, inf])

In [ ]:
arr2d[mf]=0

In [ ]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

# **Statistical Operations**

In [ ]:
#mean,std,var
arr2d.mean()

1.7777777777777777

In [ ]:
arr2d.max()

3.0

In [ ]:
arr2d.min()

0.0

In [ ]:
arr2d.std()

1.1331154474650633

In [ ]:
arr2d.var()

1.2839506172839505

In [ ]:
arr2d.squeeze()

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [ ]:
arr2d.cumsum()

array([ 0.,  0.,  1.,  3.,  5.,  7., 10., 13., 16.])

In [ ]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [ ]:
#building 2x2 array
arr=arr2d[:2,:2]

In [ ]:
arr

array([[0., 0.],
       [2., 2.]])

In [ ]:
arr2d[1:3,1:2]

array([[2.],
       [3.]])

In [ ]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [ ]:
a=arr2d.reshape(1,9)

In [ ]:
a

array([[0., 0., 1., 2., 2., 2., 3., 3., 3.]])

In [ ]:
a.ndim

2

In [ ]:
arr2d.reshape(9,1)

array([[0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.]])

In [ ]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [ ]:
a=arr2d.flatten()
a #copy

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

In [ ]:
b=arr2d.ravel()
b #reference

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

In [ ]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [ ]:
b[0]=-1

In [ ]:
arr2d

array([[-1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

# **Sequence, Repetitions, and Random Numbers**

In [ ]:
np.arange(1,5,dtype='int')

array([1, 2, 3, 4])

In [ ]:
np.arange(1,10,2,dtype='int')

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(2,50,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [ ]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
np.linspace(1,20,2)

array([ 1., 20.])

In [ ]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [ ]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
a=[1,2,3]

In [ ]:
a

[1, 2, 3]

In [ ]:
#repeating array given number of times
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
np.repeat(arr2d,3)

array([-1., -1., -1.,  0.,  0.,  0.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.])

In [ ]:
np.tile(arr2d,3)

array([[-1.,  0.,  1., -1.,  0.,  1., -1.,  0.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.]])

In [ ]:
#random numbers generation
np.random.rand()

0.309694078089905

In [ ]:
np.random.rand(1,3)

array([[0.70899486, 0.60800165, 0.12225553]])

In [ ]:
np.random.rand(3,3)

array([[0.20215232, 0.86576114, 0.26537279],
       [0.42723655, 0.41924121, 0.57763505],
       [0.76470011, 0.80776115, 0.17770051]])

In [ ]:
np.random.randn(3,3)

array([[-0.41654424, -0.17240244, -0.33252941],
       [ 0.80220716,  0.68725905, -0.94299294],
       [-0.8247923 ,  0.5720361 ,  0.06385854]])

In [ ]:
np.random.randint(0,10,[3,3])

array([[9, 1, 1],
       [0, 9, 0],
       [8, 9, 6]])

In [ ]:
#not changing random number even after reloading
np.random.seed(0)
np.random.randint(0,10,[3,3])

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [ ]:
np.random.seed(1)
np.random.randint(0,10,[3,3])

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [ ]:
np.unique(arr2d)

array([-1.,  0.,  1.,  2.,  3.])

In [ ]:
uniques,counts=np.unique(arr2d,return_counts=True)

In [ ]:
uniques

array([-1.,  0.,  1.,  2.,  3.])

In [ ]:
counts

array([1, 1, 1, 3, 3])

In [ ]:
arr=np.array([8,94,2,4,5,6,48,8,5,3,4343])
arr

array([   8,   94,    2,    4,    5,    6,   48,    8,    5,    3, 4343])

In [ ]:
index_gt10=np.where(arr>10)

In [ ]:
index_gt10

(array([ 1,  6, 10]),)

In [ ]:
arr[index_gt10]

array([  94,   48, 4343])

In [ ]:
arr[arr>10]

array([  94,   48, 4343])

In [ ]:
arr>10

array([False,  True, False, False, False, False,  True, False, False,
       False,  True])

In [ ]:
np.where(arr>10,'gt10','lt10')

array(['lt10', 'gt10', 'lt10', 'lt10', 'lt10', 'lt10', 'gt10', 'lt10',
       'lt10', 'lt10', 'gt10'], dtype='<U4')

In [ ]:
arr

array([   8,   94,    2,    4,    5,    6,   48,    8,    5,    3, 4343])

In [ ]:
arr.max()

4343

In [ ]:
arr.argmax()

10

In [ ]:
arr[arr.argmax()]

4343

In [ ]:
arr[arr.argmin()]

2

In [ ]:
arr.argmin()

2

# **Read and Write CSV file**

In [ ]:
#np.genfromtxt(),np.loadtxt()

In [ ]:
data=np.genfromtxt("https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv",delimiter=',',skip_header=1,filling_values=-1000,dtype='float')

In [ ]:
data.shape

(392, 9)

In [ ]:
np.set_printoptions(suppress=True)
data[:3]

array([[   18. ,     8. ,   307. ,   130. ,  3504. ,    12. ,    70. ,
            1. , -1000. ],
       [   15. ,     8. ,   350. ,   165. ,  3693. ,    11.5,    70. ,
            1. , -1000. ],
       [   18. ,     8. ,   318. ,   150. ,  3436. ,    11. ,    70. ,
            1. , -1000. ]])

In [ ]:
data2=np.genfromtxt("https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv",delimiter=',',skip_header=1,filling_values=-1000,dtype=None)
data2[:3]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i8'), ('f2', '<f8'), ('f3', '<i8'), ('f4', '<i8'), ('f5', '<f8'), ('f6', '<i8'), ('f7', '<i8'), ('f8', 'S38')])

In [ ]:
np.savetxt('data.csv',data,delimiter=',')

In [ ]:
data

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [ ]:
np.save('data.npy',data)

In [ ]:
np.save('data2.npz',data,data2)

In [ ]:
d=np.load('data.npy')
d

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [ ]:
d2=np.load('data2.npz.npy')

In [ ]:
d2

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [ ]:
# **Concat with row and col wise**

In [ ]:
arr1=np.zeros([4,4])
arr2=np.ones([4,4])

In [ ]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.concatenate,np.vstack,np.r_
np.concatenate([arr1,arr2],axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.vstack([arr1,arr2])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.r_[arr1,arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.concatenate([arr1,arr2],axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [ ]:
np.hstack([arr1,arr2])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [ ]:
np.c_[arr1,arr2]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

# **Sort a numpy array**

In [ ]:
arr=np.random.randint(1,10,size=[10,5])

In [ ]:
arr

array([[3, 5, 6, 3, 5],
       [3, 5, 8, 8, 2],
       [8, 1, 7, 8, 7],
       [2, 1, 2, 9, 9],
       [4, 9, 8, 4, 7],
       [6, 2, 4, 5, 9],
       [2, 5, 1, 4, 3],
       [1, 5, 3, 8, 8],
       [9, 7, 4, 8, 8],
       [5, 6, 4, 7, 9]])

In [ ]:
np.sort(arr,axis=0)

array([[1, 1, 1, 3, 2],
       [2, 1, 2, 4, 3],
       [2, 2, 3, 4, 5],
       [3, 5, 4, 5, 7],
       [3, 5, 4, 7, 7],
       [4, 5, 4, 8, 8],
       [5, 5, 6, 8, 8],
       [6, 6, 7, 8, 9],
       [8, 7, 8, 8, 9],
       [9, 9, 8, 9, 9]])

In [ ]:
si=arr[:,0].argsort()

In [ ]:
arr[si]

array([[1, 5, 3, 8, 8],
       [2, 1, 2, 9, 9],
       [2, 5, 1, 4, 3],
       [3, 5, 6, 3, 5],
       [3, 5, 8, 8, 2],
       [4, 9, 8, 4, 7],
       [5, 6, 4, 7, 9],
       [6, 2, 4, 5, 9],
       [8, 1, 7, 8, 7],
       [9, 7, 4, 8, 8]])

In [ ]:
arr

array([[3, 5, 6, 3, 5],
       [3, 5, 8, 8, 2],
       [8, 1, 7, 8, 7],
       [2, 1, 2, 9, 9],
       [4, 9, 8, 4, 7],
       [6, 2, 4, 5, 9],
       [2, 5, 1, 4, 3],
       [1, 5, 3, 8, 8],
       [9, 7, 4, 8, 8],
       [5, 6, 4, 7, 9]])

# **Working With Dates**

In [ ]:
d=np.datetime64('2019-06-02 23:10:00')

In [ ]:
d

numpy.datetime64('2019-06-02T23:10:00')

In [ ]:
d+1000

numpy.datetime64('2019-06-02T23:26:40')

In [ ]:
16*60+40

1000

In [ ]:
oneday=np.timedelta64(1,'D')

In [ ]:
oneday

numpy.timedelta64(1,'D')

In [ ]:
d+oneday

numpy.datetime64('2019-06-03T23:10:00')

In [ ]:
oneminute=np.timedelta64(1,'m')

In [ ]:
d+oneminute

numpy.datetime64('2019-06-02T23:11:00')

In [ ]:
dates=np.arange(np.datetime64('2019-06-02'),np.datetime64('2020-06-02'))
dates

array(['2019-06-02', '2019-06-03', '2019-06-04', '2019-06-05',
       '2019-06-06', '2019-06-07', '2019-06-08', '2019-06-09',
       '2019-06-10', '2019-06-11', '2019-06-12', '2019-06-13',
       '2019-06-14', '2019-06-15', '2019-06-16', '2019-06-17',
       '2019-06-18', '2019-06-19', '2019-06-20', '2019-06-21',
       '2019-06-22', '2019-06-23', '2019-06-24', '2019-06-25',
       '2019-06-26', '2019-06-27', '2019-06-28', '2019-06-29',
       '2019-06-30', '2019-07-01', '2019-07-02', '2019-07-03',
       '2019-07-04', '2019-07-05', '2019-07-06', '2019-07-07',
       '2019-07-08', '2019-07-09', '2019-07-10', '2019-07-11',
       '2019-07-12', '2019-07-13', '2019-07-14', '2019-07-15',
       '2019-07-16', '2019-07-17', '2019-07-18', '2019-07-19',
       '2019-07-20', '2019-07-21', '2019-07-22', '2019-07-23',
       '2019-07-24', '2019-07-25', '2019-07-26', '2019-07-27',
       '2019-07-28', '2019-07-29', '2019-07-30', '2019-07-31',
       '2019-08-01', '2019-08-02', '2019-08-03', '2019-

# **Numpy advanced function**

In [ ]:
#vectorize()

In [ ]:
def fool(x):
  if x%2==1:
    return x**2
  else:
    return x/2
fool(11)

121

In [ ]:
fool_v=np.vectorize(fool,otypes=[float])

In [ ]:
arr

array([[3, 5, 6, 3, 5],
       [3, 5, 8, 8, 2],
       [8, 1, 7, 8, 7],
       [2, 1, 2, 9, 9],
       [4, 9, 8, 4, 7],
       [6, 2, 4, 5, 9],
       [2, 5, 1, 4, 3],
       [1, 5, 3, 8, 8],
       [9, 7, 4, 8, 8],
       [5, 6, 4, 7, 9]])

In [ ]:
fool_v(arr)

array([[ 9., 25.,  3.,  9., 25.],
       [ 9., 25.,  4.,  4.,  1.],
       [ 4.,  1., 49.,  4., 49.],
       [ 1.,  1.,  1., 81., 81.],
       [ 2., 81.,  4.,  2., 49.],
       [ 3.,  1.,  2., 25., 81.],
       [ 1., 25.,  1.,  2.,  9.],
       [ 1., 25.,  9.,  4.,  4.],
       [81., 49.,  2.,  4.,  4.],
       [25.,  3.,  2., 49., 81.]])